### ISSUE TITLE
Advance filtering for transaction break with some query

### ISSUE THREAD

**Issue by jarindr** [omisego/ewallet#1051]
**Describe the bug**
I'm trying to use advance filter but it breaks and return 500 with this curl

```sh
curl 'http://localhost:4000/api/admin/transaction.all' \
  -H 'Accept: application/vnd.omisego.v1+json' \
  -H 'Referer: http://localhost:9000/admin/wallets/futh731508527610/transactions' \
  -H 'Authorization: OMGAdmin dXNyXzAxZGQyZXlycDNqazFhNTUzdjI2bnBtOGMxOmpMLWpGOHdlb2Q1d2hlX2hOTVcxNl9SUWJUVzE1b2M2S18tSzFULWFkeWc=' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-binary '{
    "per_page":10,
    "sort_by":"created_at",
    "sort_dir":"desc",
    "match_any":[
      {
        "field":"from_wallet",
        "comparator":"contains",
        "value":"futh731508527610"
      },{
        "field":"to_wallet",
        "comparator":"contains",
        "value":"futh731508527610"
      }
    ]
  }'
```

```
# FunctionClauseError at POST /api/admin/transaction.all

Exception:

    ** (FunctionClauseError) no function clause matching in EWallet.Web.MatchAnyQuery.do_filter/5
    
    The following arguments were given to EWallet.Web.MatchAnyQuery.do_filter/5:
    
        # 1
        false
    
        # 2
        :to_wallet
    
        # 3
        [:address, :name, :identifier, :enabled, :inserted_at, :created_at]
    
        # 4
        "contains"
    
        # 5
        "futh731508527610"
    
    Attempted function clauses (showing 3 out of 3):
    
        def do_filter(dynamic, field, -:uuid-, comparator, value)
        def do_filter(dynamic, field, -nil-, comparator, -nil = value-)
        def do_filter(dynamic, field, -nil-, comparator, value)
    
        (ewallet) lib/ewallet/web/filters/match_any_query.ex:23: EWallet.Web.MatchAnyQuery.do_filter/5
        (ewallet) lib/ewallet/web/filters/match_parser.ex:183: anonymous fn/4 in EWallet.Web.MatchParser.filter/5
        (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
        (elixir) lib/enum.ex:1990: Enum.reduce_while/3
        (ewallet) lib/ewallet/web/filters/match_parser.ex:177: EWallet.Web.MatchParser.filter/5
        (ewallet) lib/ewallet/web/filters/match_parser.ex:35: EWallet.Web.MatchParser.build_query/6
        (ewallet) lib/ewallet/web/orchestrator.ex:61: EWallet.Web.Orchestrator.build_query/3
        (ewallet) lib/ewallet/web/orchestrator.ex:37: EWallet.Web.Orchestrator.query/4
        (admin_api) lib/admin_api/v1/controllers/transaction_controller.ex:173: AdminAPI.V1.TransactionController.query_records_and_respond/3
        (admin_api) lib/admin_api/v1/controllers/transaction_controller.ex:15: AdminAPI.V1.TransactionController.action/2
        (admin_api) lib/admin_api/v1/controllers/transaction_controller.ex:15: AdminAPI.V1.TransactionController.phoenix_controller_pipeline/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phoenix) lib/phoenix/router/route.ex:147: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.plug_builder_call/2
        (admin_api) lib/admin_api/endpoint.ex:17: AdminAPI.Endpoint."call (overridable 2)"/2
        (admin_api) lib/plug/debugger.ex:122: AdminAPI.Endpoint."call (overridable 3)"/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint."call (overridable 4)"/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.call/2
    

## Connection details

### Params

    %{"match_any" => [%{"comparator" => "contains", "field" => "from_wallet", "value" => "futh731508527610"}, %{"comparator" => "contains", "field" => "to_wallet", "value" => "futh731508527610"}], "per_page" => 10, "sort_by" => "created_at", "sort_dir" => "desc"}

### Request info

  * URI: http://localhost:4000/api/admin/transaction.all
  * Query string: 

### Headers
  
  * accept: application/vnd.omisego.v1+json
  * accept-encoding: gzip, deflate, br
  * accept-language: en-US,en;q=0.9
  * authorization: OMGAdmin dXNyXzAxZGQyZXlycDNqazFhNTUzdjI2bnBtOGMxOmpMLWpGOHdlb2Q1d2hlX2hOTVcxNl9SUWJUVzE1b2M2S18tSzFULWFkeWc=
  * connection: keep-alive
  * content-length: 218
  * content-type: application/json;charset=UTF-8
  * host: localhost:4000
  * origin: http://localhost:9000
  * referer: http://localhost:9000/admin/wallets/futh731508527610/transactions
  * user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36

### Session

    nil
```

**Comment by unnawut** [comment]
@jarindr Can you try with `"field":"from_wallet.address"` and `"field":"from_wallet.address"`?

It'll probably solve your issue and this internal server error will be fixed separately.
