### ISSUE TITLE
Randomly Failing to retrieve a transfer after insert

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#224]
# Subject of the issue

Randomly Failing to retrieve a transfer after insert in:

```elixir
  def insert(attrs) do
    changeset = changeset(%Transfer{}, attrs)
    opts = [on_conflict: :nothing, conflict_target: :idempotency_token]

    case Repo.insert(changeset, opts) do
      {:ok, transfer} ->
        {:ok, get_by_idempotency_token(transfer.idempotency_token)}

      changeset ->
        changeset
    end
  end
```

# Your environment

Staging environment, using Ruby SDK or iOS SDK.

# Steps to reproduce

1. Get Ruby SDK
2. Replace the config in `env.rb` with real values
3. Run 

```
~/src/ruby-sdk on  T305-renaming! ⌚ 16:05:55
$ rspec ./spec/omisego/wallet_spec.rb                                                                                                                                                                                            ‹ruby-2.3.3›

OmiseGO::Wallet
  .all
    retrieves the list of wallets
  .credit
    with valid params
      credits the user's wallet
    with params account_id and account_address
      credits the user's wallet (FAILED - 1)
  .debit
    with valid params
      debits the user's wallet (FAILED - 2)
    with params account_id and account_address
      debit/s the user's wallet

Failures:

  1) OmiseGO::Wallet.credit with params account_id and account_address credits the user's wallet
     Failure/Error: expect(wallets).to be_kind_of OmiseGO::List
       expected #<OmiseGO::Error:70175132363600 code: server:internal_server_error, description: Something went wrong on the server, messages: > to be a kind of OmiseGO::List
     # ./spec/omisego/wallet_spec.rb:67:in `block (5 levels) in <module:OmiseGO>'
     # /Users/thibault/.rvm/gems/ruby-2.3.3/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/thibault/.rvm/gems/ruby-2.3.3/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/omisego/wallet_spec.rb:55:in `block (4 levels) in <module:OmiseGO>'

  2) OmiseGO::Wallet.debit with valid params debits the user's wallet
     Failure/Error: expect(wallets).to be_kind_of OmiseGO::List
       expected #<OmiseGO::Error:70175123941460 code: server:internal_server_error, description: Something went wrong on the server, messages: > to be a kind of OmiseGO::List
     # ./spec/omisego/wallet_spec.rb:87:in `block (5 levels) in <module:OmiseGO>'
     # /Users/thibault/.rvm/gems/ruby-2.3.3/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/thibault/.rvm/gems/ruby-2.3.3/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/omisego/wallet_spec.rb:76:in `block (4 levels) in <module:OmiseGO>'

Finished in 3.04 seconds (files took 0.46432 seconds to load)
5 examples, 2 failures

Failed examples:

rspec ./spec/omisego/wallet_spec.rb:54 # OmiseGO::Wallet.credit with params account_id and account_address credits the user's wallet
rspec ./spec/omisego/wallet_spec.rb:75 # OmiseGO::Wallet.debit with valid params debits the user's wallet
```

# Expected behavior

The response should be successful instead of `500`. 

# Actual behavior

The server returns `500`.

# Research

The server crashes because `nil` is passed as the first argument in those functions:

```elixir
  defp process_with_transfer(%Transfer{status: "pending"} = transfer, wallets, token) do
    transfer
    |> TransferGate.process()
    |> process_with_transfer(wallets, token)
  end

  defp process_with_transfer(%Transfer{status: "confirmed"} = transfer, wallets, token) do
    {:ok, transfer, wallets, token}
  end

  defp process_with_transfer(%Transfer{status: "failed"} = transfer, _wallets, _token) do
    resp = transfer.ledger_response
    {:error, transfer, resp["code"], resp["description"]}
  end
```

Which happens because of `get_by_idempotency_token` is returning `nil` in the following code, which is not supposed to happen becasue either a record has just been inserted or has been inserted in another process.

```elixir
  def insert(attrs) do
    changeset = changeset(%Transfer{}, attrs)
    opts = [on_conflict: :nothing, conflict_target: :idempotency_token]

    case Repo.insert(changeset, opts) do
      {:ok, transfer} ->
        {:ok, get_by_idempotency_token(transfer.idempotency_token)}

      changeset ->
        changeset
    end
  end
```

# Attempts

- Surround with Transaction PR #219 
- Retries #222 

Thoughts? I ran out of ideas except for the retries with delay to solve the fact that the DB state does not seem up to date.

**Comment by T-Dnzt** [comment]
@sirn @unnawut 

After merging #222, it keeps happening. After 3 fails, the following was returned to the client (which can be handled, but I want to know why it's happening!!):

```ruby
#<OmiseGO::Error:70277965001840 code: db:inserted_transaction_could_not_be_loaded, description: We co.... Please try submitting the same transaction again (with identical idempontecy token!)., messages: > to be a kind of OmiseGO::List
```

**Comment by T-Dnzt** [comment]
However, with this error, it's now possible to send the transaction again (with same idempotency token) and the second request always work as expected (since it's getting the record from the DB correctly).

**Comment by T-Dnzt** [comment]
Scratch that, it still happens. Even two requests in a row (the second one only happening if the first one got `db:inserted_transaction_could_not_be_loaded`, the second can still get a `500` with the following output:

```
Request: POST /api/user.debit_wallet
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in EWallet.TransferGate.update_transfer/2
        (ewallet) lib/ewallet/gates/transfer_gate.ex:93: EWallet.TransferGate.update_transfer({:error, #Ecto.Changeset<action: :insert, changes: %{correlation_id: "cb1a4fec-55fc-4c43-a938-772eca5f18ff", encrypted_metadata: %{}, encryption_version: <<83, 66, 88, 1>>, metadata: %{}, transactions: [#Ecto.Changeset<action: :insert, changes: %{amount: 10000, token_id: "tok_OMG_01ccmny8yne44b188287d44498", type: "debit", wallet_address: "000d54d4-4db6-462f-aa0b-6f138bb80bf4"}, errors: [], data: #LocalLedgerDB.Transaction<>, valid?: true>, #Ecto.Changeset<action: :insert, changes: %{amount: 10000, token_id: "tok_OMG_01ccmny8yne44b188287d44498", type: "credit", wallet_address: "b0f8d17e-85be-4261-852b-d7aa6252476d"}, errors: [], data: #LocalLedgerDB.Transaction<>, valid?: true>]}, errors: [correlation_id: {"has already been taken", []}], data: #LocalLedgerDB.Entry<>, valid?: false>}, %EWalletDB.Transfer{__meta__: #Ecto.Schema.Metadata<:loaded, "transfer">, amount: 10000, encrypted_metadata: %{}, encryption_version: <<83, 66, 88, 1>>, from: "000d54d4-4db6-462f-aa0b-6f138bb80bf4", from_wallet: %EWalletDB.Wallet{__meta__: #Ecto.Schema.Metadata<:loaded, "wallet">, account: #Ecto.Association.NotLoaded<association :account is not loaded>, account_uuid: nil, address: "000d54d4-4db6-462f-aa0b-6f138bb80bf4", encrypted_metadata: %{}, encryption_version: <<83, 66, 88, 1>>, identifier: "primary", inserted_at: ~N[2018-01-26 20:35:57.974131], metadata: %{}, name: "primary", token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_uuid: nil, updated_at: ~N[2018-01-26 20:35:57.974142], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "48236187-9c5c-4568-8cdf-f0233d035574", uuid: "8d1be0a9-452d-49cc-9d24-9ef2cc2fa8a6"}, id: "tfr_01cf7p59vs3kbn77bdxtv06rye", idempotency_token: "cb1a4fec-55fc-4c43-a938-772eca5f18ff", inserted_at: ~N[2018-06-05 09:58:59.193275], ledger_response: nil, metadata: %{}, payload: %{"account_address" => "b0f8d17e-85be-4261-852b-d7aa6252476d", "account_id" => "acc_01C4T2Y5SFYASXXYANV96MQQC9", "amount" => 10000, "encrypted_metadata" => %{}, "idempotency_token" => "cb1a4fec-55fc-4c43-a938-772eca5f18ff", "metadata" => %{}, "provider_user_id" => "provider_user_id01", "token_id" => "tok_OMG_01ccmny8yne44b188287d44498", "type" => "debit", "user_address" => nil}, status: "pending", to: "b0f8d17e-85be-4261-852b-d7aa6252476d", to_wallet: %EWalletDB.Wallet{__meta__: #Ecto.Schema.Metadata<:loaded, "wallet">, account: #Ecto.Association.NotLoaded<association :account is not loaded>, account_uuid: "edbb9557-c37f-4511-b3ff-794fc553b8cf", address: "b0f8d17e-85be-4261-852b-d7aa6252476d", encrypted_metadata: %{}, encryption_version: <<83, 66, 88, 1>>, identifier: "primary", inserted_at: ~N[2018-01-26 20:35:56.955577], metadata: %{}, name: "primary", token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_uuid: nil, updated_at: ~N[2018-01-26 20:35:56.955588], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: nil, uuid: "493a812e-8b5b-42a3-b115-4b410e9d8f7c"}, token: %EWalletDB.Token{__meta__: #Ecto.Schema.Metadata<:loaded, "token">, account: #Ecto.Association.NotLoaded<association :account is not loaded>, account_uuid: "edbb9557-c37f-4511-b3ff-794fc553b8cf", description: nil, encrypted_metadata: %{}, encryption_version: <<83, 66, 88, 1>>, html_entity: nil, id: "tok_OMG_01ccmny8yne44b188287d44498", inserted_at: ~N[2018-01-26 20:35:57.423879], iso_code: nil, iso_numeric: nil, locked: false, metadata: %{"migration_original_id" => "tok_OMG_01C4T2Y6BFEJC84SF91GJBTGMY"}, name: "OmiseGO", short_symbol: nil, smallest_denomination: nil, subunit: nil, subunit_to_unit: 10000, symbol: "OMG", symbol_first: true, updated_at: ~N[2018-01-26 20:35:57.423894], uuid: "e44b1882-87d4-4498-91d2-a5762593a194"}, token_uuid: "e44b1882-87d4-4498-91d2-a5762593a194", type: "internal", updated_at: ~N[2018-06-05 09:58:59.193293], uuid: "467c8de0-dd62-42e2-9c95-e2d587eea447"})
        (ewallet) lib/ewallet/gates/transaction_gate.ex:137: EWallet.TransactionGate.process_with_transfer/3
        (ewallet_api) lib/ewallet_api/v1/controllers/transfer_controller.ex:78: EWalletAPI.V1.TransferController.credit_or_debit/3
        (ewallet_api) lib/ewallet_api/v1/controllers/transfer_controller.ex:1: EWalletAPI.V1.TransferController.action/2
        (ewallet_api) lib/ewallet_api/v1/controllers/transfer_controller.ex:1: EWalletAPI.V1.TransferController.phoenix_controller_pipeline/2
        (ewallet_api) lib/ewallet_api/endpoint.ex:1: EWalletAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phoenix) lib/phoenix/router/route.ex:163: Phoenix.Router.Route.forward/4
```
