### ISSUE TITLE
Cannot login to admin panel using docker-compose version

### ISSUE THREAD

**Issue by LyXman** [omisego/ewallet#439]
# Subject of the issue

I have setup the ewallet as described in the docs using the docker-compose file approach. Everything goes well and the sample database is created, but when I try to login with the self-made credentials following error occurs every time:

ewallet_1   | 16:35:58.494 request_id=2l7cm20hcoc05ldga80005n1 [info] GET /admin
ewallet_1   | 16:35:58.593 request_id=2l7cm20hcoc05ldga80005n1 [info] Sent 200 in 99ms
ewallet_1   | 16:36:08.673 request_id=2l7cm2jg7leusgo60g0005oh [info] POST /api/admin/admin.login
ewallet_1   | 16:36:08.796 request_id=2l7cm2jg7leusgo60g0005oh [info] Sent 500 in 123ms
ewallet_1   | 16:36:08.801 [error] #PID<0.1165.0> running UrlDispatcher.Plug terminated
ewallet_1   | Server: localhost:4000 (http)
ewallet_1   | Request: POST /api/admin/admin.login
ewallet_1   | ** (exit) an exception was raised:
ewallet_1   |     ** (ArgumentError) argument error
ewallet_1   |         :erlang.iolist_to_binary(:error)
ewallet_1   |         (poison) lib/poison/parser.ex:35: Poison.Parser.parse/2
ewallet_1   |         (poison) lib/poison/parser.ex:51: Poison.Parser.parse!/2
ewallet_1   |         (poison) lib/poison.ex:83: Poison.decode!/2
ewallet_1   |         (ewallet_db) lib/cloak/field.ex:48: EWalletDB.Encrypted.Map.load/1
ewallet_1   |         (ecto) lib/ecto/type.ex:647: Ecto.Type.process_loaders/3
ewallet_1   |         (ecto) lib/ecto/schema.ex:1416: Ecto.Schema.load!/5
ewallet_1   |         (ecto) lib/ecto/schema.ex:1399: Ecto.Schema.__load__/5

# Your environment

OS: Ubuntu 16.04 LTS
Docker: 18.03.1-ce, build 9ee9f40
Docker-Compose: 1.13.0, build 1719ceb

# Other log entries from the docker images

mailhog_1   | [APIv1] KEEPALIVE /api/v1/events
postgres_1  | FATAL:  role "root" does not exist

**Comment by unnawut** [comment]
Hey LyXman, could you share us your `docker-compose.yml` file? Looks like it's having trouble decrypting the encrypted metadata from the database.

**Comment by LyXman** [comment]
Hi unnawut,

thanks for the fast response.
Here is my docker-compose.yml file:

version: "3"
services:
  postgres:
    image: postgres:9.6.9-alpine
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRESQL_PASSWORD: passw0rd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 3

  mailhog:
    image: mailhog/mailhog:v1.0.0
    restart: always
    networks:
      - internal

  ewallet:
    image: omisego/ewallet:latest
    restart: always
    networks:
      - internal
      - external
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:passw0rd@postgres:5432/ewallet"
      LOCAL_LEDGER_DATABASE_URL: "postgresql://postgres:passw0rd@postgres:5432/local_ledger"
      EWALLET_SECRET_KEY: "W1e92PuD5673Ab/q8zL53XxsoSUSrh9+LhFUuDY/93s="
      LOCAL_LEDGER_SECRET_KEY: "gxUwX2S3RFOmsKZ9tsbpoEExtvHygoaFYcmxflsAdgc="
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports:
      - 4000:4000

networks:
  external:
  internal:

volumes:
  postgres-db:

It's basically a copy-paste version of the tutorial (https://github.com/omisego/ewallet/blob/master/docs/setup/docker.md) with random secret keys.

Cheers

**Comment by unnawut** [comment]
Thanks for the info! Your `docker-compose.yml` looks fine to me.

I'm suspecting it is to do with the different secret keys being loaded by the application and while running the commands. Could you try this set of commands?

```sh
# 1. Start from scratch by deleting all containers and volumes associated with `docker-compose.yml`
docker-compose down --volumes

# 2. Spin up the containers
docker-compose up

# 3. Run the migrations with `MIX_ENV=prod`
docker exec -it <your_container_id> sh -c "MIX_ENV=prod mix do ecto.create, ecto.migrate"

# 4. Run the seed with `MIX_ENV=prod`
docker exec -it <your_container_id> sh -c "MIX_ENV=prod mix seed"
```

Now try login with the email/password from the last command above.

**Comment by unnawut** [comment]
Happy to hear that! Also many thanks for letting us know about adding the `BASE_URL`.

Created #442 to fix this.
