### ISSUE TITLE
Error when filtering for nil

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#531]
When filtering for nil, the following error is thrown:

```elixir
# ArgumentError at POST /api/admin/wallet.all

Exception:

    ** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
        (ecto) lib/ecto/query/builder.ex:517: Ecto.Query.Builder.not_nil!/1
        (ewallet) lib/ewallet/web/filters/match_all_query.ex:40: anonymous fn/4 in EWallet.Web.MatchAllQuery.do_filter_assoc/6
        (ecto) lib/ecto/query/builder/dynamic.ex:50: Ecto.Query.Builder.Dynamic.expand/3
        (ecto) lib/ecto/query/builder/dynamic.ex:32: Ecto.Query.Builder.Dynamic.fully_expand/2
        (ecto) lib/ecto/query/builder/filter.ex:93: Ecto.Query.Builder.Filter.filter!/6
        (ecto) lib/ecto/query/builder/filter.ex:114: Ecto.Query.Builder.Filter.filter!/7
        (ewallet) lib/ewallet/web/filters/match_parser.ex:21: EWallet.Web.MatchParser.build_query/5
        (ewallet) lib/ewallet/web/orchestrator.ex:34: EWallet.Web.Orchestrator.build_query/3
        (ewallet) lib/ewallet/web/orchestrator.ex:23: EWallet.Web.Orchestrator.query/4
        (admin_api) lib/admin_api/v1/controllers/wallet_controller.ex:87: AdminAPI.V1.WalletController.do_all/3
        (admin_api) lib/admin_api/v1/controllers/wallet_controller.ex:1: AdminAPI.V1.WalletController.action/2
        (admin_api) lib/admin_api/v1/controllers/wallet_controller.ex:1: AdminAPI.V1.WalletController.phoenix_controller_pipeline/2
        (admin_api) lib/admin_api/endpoint.ex:1: AdminAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phoenix) lib/phoenix/router/route.ex:163: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (admin_api) lib/admin_api/endpoint.ex:1: AdminAPI.Endpoint.plug_builder_call/2
        (admin_api) lib/plug/debugger.ex:102: AdminAPI.Endpoint."call (overridable 3)"/2
        (admin_api) lib/admin_api/endpoint.ex:1: AdminAPI.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
```

The filter should filter for nil successfully, or return a proper error object when nil filtering is not supported.

**Comment by mederic-p** [comment]
You could also add new comparators `is_nil` or `is_not_nil` and ignore the `value` param. I don't know which solution is the most common.
