### ISSUE TITLE
Error 500 when attempting to assign a new admin

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#536]
**Error stacktrace:**

```elixir
# ArgumentError at POST /api/admin/account.assign_user

Exception:

    ** (ArgumentError) argument error
        (stdlib) :binary.match("http://localhost:9000/admin/invite/?token={token}&email={email}", nil)
        (elixir) lib/string.ex:1963: String.starts_with?/2
        (elixir) lib/enum.ex:2864: Enum.any_list/2
        (admin_api) lib/admin_api/v1/controllers/account_membership_controller.ex:87: AdminAPI.V1.AccountMembershipController.validate_redirect_url/1
        (admin_api) lib/admin_api/v1/controllers/account_membership_controller.ex:38: AdminAPI.V1.AccountMembershipController.assign_user/2
        (admin_api) lib/admin_api/v1/controllers/account_membership_controller.ex:1: AdminAPI.V1.AccountMembershipController.action/2
        (admin_api) lib/admin_api/v1/controllers/account_membership_controller.ex:1: AdminAPI.V1.AccountMembershipController.phoenix_controller_pipeline/2
        (admin_api) lib/admin_api/endpoint.ex:1: AdminAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phoenix) lib/phoenix/router/route.ex:163: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (admin_api) lib/admin_api/endpoint.ex:1: AdminAPI.Endpoint.plug_builder_call/2
        (admin_api) lib/plug/debugger.ex:102: AdminAPI.Endpoint."call (overridable 3)"/2
        (admin_api) lib/admin_api/endpoint.ex:1: AdminAPI.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/jarindr/ewallet/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Request payload:**

```
{"email":"test232@gmail.com","redirect_url":"http://localhost:9000/admin/invite/?token={token}&email={email}","account_id":"acc_01ctd3qywef25p4j1gtc1pm340","role_name":"admin"}
```

**Comment by unnawut** [comment]
Couldn't reproduce so far. Waiting for more information.

**Comment by unnawut** [comment]
Closing until more information is provided.
