### ISSUE TITLE
Random test failure: test allowed?/4 keeps the higher priority membership in a descendant account

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#653]
The move from Jenkins to CircleCI might have changed the machine profile significantly enough that tests are running faster and slower to some degree, and hence impacts what tests are executed in parallel and so we're seeing more random test failures.

https://circleci.com/gh/omisego/ewallet/1587:

```ex
  1) test allowed?/4 keeps the higher priority membership in a descendant account (EWalletDB.MembershipCheckerTest)
     test/ewallet_db/membership_checker_test.exs:173
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
     
         * unique: role_priority_index
     
     If you would like to convert this constraint into an error, please
     call unique_constraint/3 in your changeset and define the proper
     constraint name. The changeset has not defined any constraint.
     
     code: insert(:membership, user: ctx.originator, account: ctx.account_3, role: ctx.role_high)
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:495: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
       (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
       (ecto) lib/ecto/repo/schema.ex:481: Ecto.Repo.Schema.constraints_to_errors/3
       (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:691: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:131: Ecto.Repo.Schema.insert!/4
       (ewallet_db) test/support/factory.ex:211: EWalletDB.Factory.membership_factory/0
       (ex_machina) lib/ex_machina.ex:170: ExMachina.build/3
       (ewallet_db) test/support/factory.ex:19: EWalletDB.Factory.insert/2
       test/ewallet_db/membership_checker_test.exs:175: (test)
```

**Comment by unnawut** [comment]
Sorry false alarm. The error was part of an in-progress PR.

**Comment by unnawut** [comment]
Hello. It is back: https://circleci.com/gh/omisego/ewallet/2030
