### ISSUE TITLE
Activity Logs wallets don't have balances, which need to be preloaded

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#668]
```
[error] #PID<0.1966.0> running UrlDispatcher.Plug (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: POST /api/admin/activity_log.all
** (exit) an exception was raised:
    ** (KeyError) key :balances not found in: %EWalletDB.Wallet{__meta__: #Ecto.Schema.Metadata<:loaded, "wallet">, account: nil, account_uuid: nil, address: "gnis000000000000", enabled: true, encrypted_metadata: %{}, identifier: "genesis", inserted_at: ~N[2019-01-17 07:34:27.677127], metadata: %{}, name: "genesis", originator: nil, updated_at: ~N[2019-01-17 07:34:27.677135], user: nil, user_uuid: nil, uuid: "3d3c3138-226c-42ec-a230-cd4160cf3615"}
        (ewallet) lib/ewallet/web/v1/serializers/wallet_serializer.ex:59: EWallet.Web.V1.WalletSerializer.serialize/1
        (ewallet) lib/ewallet/web/v1/serializers/activity_log_serializer.ex:46: EWallet.Web.V1.ActivityLogSerializer.serialize/1
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/map.ex:736: Map.update!/3
        (ewallet) lib/ewallet/web/v1/serializers/paginator_serializer.ex:27: EWallet.Web.V1.PaginatorSerializer.serialize/2
        (admin_api) lib/admin_api/v1/views/activity_log_view.ex:27: AdminAPI.V1.ActivityLogView.render/2
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (admin_api) lib/admin_api/v1/controllers/activity_log_controller.ex:15: AdminAPI.V1.ActivityLogController.action/2
        (admin_api) lib/admin_api/v1/controllers/activity_log_controller.ex:15: AdminAPI.V1.ActivityLogController.phoenix_controller_pipeline/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phoenix) lib/phoenix/router/route.ex:147: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.plug_builder_call/2
        (admin_api) lib/admin_api/endpoint.ex:17: AdminAPI.Endpoint."call (overridable 2)"/2
        (admin_api) lib/plug/debugger.ex:122: AdminAPI.Endpoint."call (overridable 3)"/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint."call (overridable 4)"/2
```

**Comment by T-Dnzt** [comment]
Fixed in #679.
