### ISSUE TITLE
UndefinedFunctionError on some /api/client/me.get_wallets calls

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#811]
An exception was reported from one of the running environments: 

Endpoint: `/api/client/me.get_wallets`

Exception: `function nil.address/0 is undefined or private`

Stacktrace:

```
nil.address/0
(ewallet) lib/ewallet/fetchers/balance_fetcher.ex:105: EWallet.BalanceFetcher.query_and_add_balances/1
(ewallet) lib/ewallet/fetchers/balance_fetcher.ex:34: EWallet.BalanceFetcher.all/1
(ewallet_api) lib/ewallet_api/v1/controllers/self_controller.ex:32: EWalletAPI.V1.SelfController.get_wallets/2
(ewallet_api) lib/ewallet_api/v1/controllers/self_controller.ex:15: EWalletAPI.V1.SelfController.action/2
(ewallet_api) lib/ewallet_api/v1/controllers/self_controller.ex:15: EWalletAPI.V1.SelfController.phoenix_controller_pipeline/2
(ewallet_api) lib/ewallet_api/endpoint.ex:15: EWalletAPI.Endpoint.instrument/4
(phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
```

**Comment by unnawut** [comment]
This happened with an implementation before #822 was merged. Since a lot has changed since that PR, I'm closing this down until it resurfaces.
