### ISSUE TITLE
/exchange_pair.create rate doesn't accept string and returning 500

### ISSUE THREAD

**Issue by jarindr** [omisego/ewallet#996]
/exchange_pair.update too.

request:
```
{"from_token_id":"tok_ETH_01d7brbvs76ceqyp683enns91a","to_token_id":"tok_KNC_01d7brbvnftq9efg039emzbch9","rate":"1000","sync_opposite":true}
```

response:
```
# ArithmeticError at POST /api/admin/exchange_pair.create

Exception:

    ** (ArithmeticError) bad argument in arithmetic expression
        (ewallet) lib/ewallet/gates/exchange_pair_gate.ex:60: EWallet.ExchangePairGate.insert/2
        (ewallet) lib/ewallet/gates/exchange_pair_gate.ex:30: anonymous fn/1 in EWallet.ExchangePairGate.insert/1
        (ecto_sql) lib/ecto/adapters/sql.ex:820: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
        (db_connection) lib/db_connection.ex:1355: DBConnection.run_transaction/4
        (admin_api) lib/admin_api/v1/controllers/exchange_pair_controller.ex:70: AdminAPI.V1.ExchangePairController.create/2
        (admin_api) lib/admin_api/v1/controllers/exchange_pair_controller.ex:15: AdminAPI.V1.ExchangePairController.action/2
        (admin_api) lib/admin_api/v1/controllers/exchange_pair_controller.ex:15: AdminAPI.V1.ExchangePairController.phoenix_controller_pipeline/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phoenix) lib/phoenix/router/route.ex:147: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.plug_builder_call/2
        (admin_api) lib/admin_api/endpoint.ex:17: AdminAPI.Endpoint."call (overridable 2)"/2
        (admin_api) lib/plug/debugger.ex:122: AdminAPI.Endpoint."call (overridable 3)"/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint."call (overridable 4)"/2
        (admin_api) lib/admin_api/endpoint.ex:15: AdminAPI.Endpoint.call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/jarindr/ewallet/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
    

## Connection details

### Params

    %{"from_token_id" => "tok_ETH_01d7brbvs76ceqyp683enns91a", "rate" => "1000", "sync_opposite" => true, "to_token_id" => "tok_KNC_01d7brbvnftq9efg039emzbch9"}

### Request info

  * URI: http://localhost:4000/api/admin/exchange_pair.create
  * Query string: 

### Headers
  
  * accept: application/vnd.omisego.v1+json
  * accept-encoding: gzip, deflate, br
  * accept-language: en-US,en;q=0.9
  * authorization: OMGAdmin dXNyXzAxZDdicmJzbmhmemNuMHlucmNlenJ3Z3dxOlJWczFJclg2M25CZWpsUzJhUWxVT0IxMUdONk9fSlNxRXU5S2FsNUdBcDA=
  * connection: keep-alive
  * content-length: 140
  * content-type: application/json;charset=UTF-8
  * host: localhost:4000
  * origin: http://localhost:9000
  * referer: http://localhost:9000/admin/tokens/tok_ETH_01d7brbvs76ceqyp683enns91a
  * user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

### Session

    nil

```

**Comment by unnawut** [comment]
Closed by #1000
